# Generated by Django 3.1.6 on 2021-02-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210215_2352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivateAccount',
        ),
    ]
