# Generated by Django 3.1.6 on 2021-02-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_activateaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForgotPassword',
        ),
    ]
